version: "2"

services:
  mongo:
    image: mongo:3.4
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - network-reactive

  reactive-kv:
    build:
      context: ../../solution/Task_1_to_3/
    image: reactive-kv-spring
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
    ports:
      - "8080:8080"
    networks:
      - network-reactive

volumes:
  mongodata:

networks:
  network-reactive: